config/routes.rb
Rails.application.routes.draw do
  resources :negotiations
  resources :open_house_times
  resources :memos
  resources :tickets
  resources :hits
  resources :feeds
  post '/adverts/:id/add_another_day' => 'adverts#add_another_day'
  resources :adverts
  resources :offers
  get '/pages/refresh_offers_portlet' => 'pages#refresh_offers_portlet'
  get '/properties/:id/images_tot' => 'properties#images_tot'
  post '/tickets/:id/add_memo' => 'tickets#add_memo'
  devise_for :users
  post '/users/:id' => 'users#update'
  get '/users/:id/show_picture' => 'users#show_picture'
  get '/offers/review/:id' => 'offers#review'
  get '/pages/view_offer/:id' => 'pages#view_offer'
  get '/users/create_admin'
  get '/users/:id' => 'users#show'
  post '/properties/img_post' => 'properties#img_post'
  post '/properties/img_rm' => 'properties#img_rm'
  get 'pages/more_filters'
  get 'pages/landing'
  get 'pages/browse'
  get 'pages/untitled'
  get 'pages/listing_details/:listing_id' => 'pages#listing_details'
  get 'pages/search'
  get 'pages/offer_1'
  get 'pages/offer_2'
  get 'pages/offer_3'
  get 'pages/offer_4'
  get 'pages/offer_5'
  get 'pages/offer_6'
  put '/pages/best_in_place_update'
  put '/pages/offer_5' => 'pages#put_todo'
  get '/pages/user_dashboard'
  get '/pages/admin_dashboard'
  post 'api/favorite_on'
  post 'api/favorite_off'
  root 'pages#landing'
  resources :users do
    resources :adverts
  end
  resources :properties

end

app/models/feed.rb
class Feed < ActiveRecord::Base
  belongs_to :user
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy]

  # GET /feeds
  # GET /feeds.json
  def index
    @feeds = Feed.all
  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show
  end

  # GET /feeds/new
  def new
    @feed = Feed.new
  end

  # GET /feeds/1/edit
  def edit
  end

  # POST /feeds
  # POST /feeds.json
  def create
    @feed = Feed.new(feed_params)

    respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, notice: 'Feed was successfully created.' }
        format.json { render :show, status: :created, location: @feed }
      else
        format.html { render :new }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feeds/1
  # PATCH/PUT /feeds/1.json
  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, notice: 'Feed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feed
      @feed = Feed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feed_params
      params.require(:feed).permit(:message, :user_id)
    end
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_form.html.slim
= form_for @feed do |f|
  - if @feed.errors.any?
    #error_explanation
      h2 = "#{pluralize(@feed.errors.count, "error")} prohibited this feed from being saved:"
      ul
        - @feed.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :message
    = f.text_field :message
  .field
    = f.label :user
    = f.text_field :user
  .actions = f.submit

app/views/feeds/edit.html.slim
h1 Editing feed

== render 'form'

= link_to 'Show', @feed
'|
= link_to 'Back', feeds_path

app/views/feeds/index.html.slim
h1 Listing feeds

table
  thead
    tr
      th Message
      th User
      th
      th
      th

  tbody
    - @feeds.each do |feed|
      tr
        td = feed.message
        td = feed.user
        td = link_to 'Show', feed
        td = link_to 'Edit', edit_feed_path(feed)
        td = link_to 'Destroy', feed, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Feed', new_feed_path

app/views/feeds/new.html.slim
h1 New feed

== render 'form'

= link_to 'Back', feeds_path

app/views/feeds/show.html.slim
p#notice = notice

p
  strong Message:
  = @feed.message
p
  strong User:
  = @feed.user

= link_to 'Edit', edit_feed_path(@feed)
'|
= link_to 'Back', feeds_path