config/routes.rb
Rails.application.routes.draw do
  resources :negotiations
  resources :open_house_times
  resources :memos
  resources :tickets
  resources :hits
  resources :feeds
  post '/adverts/:id/add_another_day' => 'adverts#add_another_day'
  resources :adverts
  resources :offers
  get '/pages/refresh_offers_portlet' => 'pages#refresh_offers_portlet'
  get '/properties/:id/images_tot' => 'properties#images_tot'
  post '/tickets/:id/add_memo' => 'tickets#add_memo'
  devise_for :users
  post '/users/:id' => 'users#update'
  get '/users/:id/show_picture' => 'users#show_picture'
  get '/offers/review/:id' => 'offers#review'
  get '/pages/view_offer/:id' => 'pages#view_offer'
  get '/users/create_admin'
  get '/users/:id' => 'users#show'
  post '/properties/img_post' => 'properties#img_post'
  post '/properties/img_rm' => 'properties#img_rm'
  get 'pages/more_filters'
  get 'pages/landing'
  get 'pages/browse'
  get 'pages/untitled'
  get 'pages/listing_details/:listing_id' => 'pages#listing_details'
  get 'pages/search'
  get 'pages/offer_1'
  get 'pages/offer_2'
  get 'pages/offer_3'
  get 'pages/offer_4'
  get 'pages/offer_5'
  get 'pages/offer_6'
  put '/pages/best_in_place_update'
  put '/pages/offer_5' => 'pages#put_todo'
  get '/pages/user_dashboard'
  get '/pages/admin_dashboard'
  post 'api/favorite_on'
  post 'api/favorite_off'
  root 'pages#landing'
  resources :users do
    resources :adverts
  end
  resources :properties

end

app/models/advert.rb
class Advert < ActiveRecord::Base
  belongs_to :user
  belongs_to :property
  has_many :open_house_times
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :property
  belongs_to :user
end

app/models/feature.rb
class Feature < ActiveRecord::Base
  has_and_belongs_to_many :properties
end

# == Schema Information
#
# Table name: features
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/models/feed.rb
class Feed < ActiveRecord::Base
  belongs_to :user
end

app/models/hit.rb
class Hit < ActiveRecord::Base

  def self.last_30_days(user)
    ret_val = []
    30.times do |i|
      if ! user
        ret_val.push( Hit.where(htime: (Time.now()-(i+1).days).end_of_day..(Time.now()-i.days).end_of_day).size   )
      else
        ret_val.push( Hit.where(user_id: user.id, htime: (Time.now()-(i+1).days).end_of_day..(Time.now()-i.days).end_of_day).size   )
      end
    end
    #(1..30).each do |i|
    #  range_start = (Time.now() - i.days).midnight()
    #  range_end = (Time.now() - i.days + 1.day).midnight()
    #  ret_val.push( Hit.where(htime: range_start..range_end).size   )
    #end
    ret_val
  end
end

app/models/memo.rb
class Memo < ActiveRecord::Base
  belongs_to :ticket
end

app/models/negotiation.rb
class Negotiation < ActiveRecord::Base
end

app/models/offer.rb
class Offer < ActiveRecord::Base
  belongs_to :user
  belongs_to :property
end

app/models/property.rb
class Property < ActiveRecord::Base
  has_many :favorites
  has_many :adverts
  has_many :users, through: :favorites
  has_many :users, through: :adverts

  def is_favorite?(curr_user)
    Favorite.where(user_id: curr_user.id, property_id: self.id).size == 1
  end

  def sf
    "$#{self.price/self.area}/sf" rescue ""
  end

  def combined_address
    "#{address} #{city} #{state} #{zip}"
  end

  # accounts for deleted images
  def images_tot_available
    ret_val = images_tot
    ret_val = 0 if ! images_tot
    a = images_deleted
    a = "[]" if images_deleted.blank?
    a = JSON.parse(images_deleted) rescue []
    ret_val = images_tot - a.size
  end

  def is_photo_deleted?(index)
    deleteds = JSON.parse(images_deleted) rescue []
    deleteds.include?(index.to_s)
  end
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base

  def last_sayer
    User.find(Memo.where(ticket_id: self.id).all.order(created_at: :desc).first.mfrom) rescue User.none
  end

  def last_sayer_id
    User.find(Memo.where(ticket_id: self.id).all.order(created_at: :desc).first.mfrom).id rescue nil
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :favorites
  has_many :properties, through: :favorites
  has_many :adverts
  has_many :properties, through: :adverts
  has_many :feeds

  def offers
    all_offers = Offer.all
    return all_offers.select { |offer|
      Advert.where(user_id: self.id, property_id: offer.property_id).all.size > 0
    }
  end

  def pending_offers
    all_offers = Offer.all
    offers =  all_offers.select { |offer|
      Advert.where(user_id: self.id, property_id: offer.property_id).all.size > 0
    }
    offers.select { |x| x.reviewed == nil || x.reviewed == false }
  end

  def total_views
    properties = self.adverts.pluck(:property_id)
    hits = Hit.all.select { |h| properties.include? h.property_id }
    hits.size
  end

  # given a time in integer format, returns hits that
  # happened on that day &&
  # was for a property listed by this user
  def hits_for_day(timestamp)
    properties = Advert.where(user_id: self.id).pluck(:property_id)
    beg_time = Time.zone.at(timestamp).beginning_of_day
    end_time = Time.zone.at(timestamp).end_of_day
    Hit.where("property_id IN (?)", properties).where(created_at: beg_time..end_time).all
  end

  # participatng tickets  
  def tickets
    #memos = Memo.where("mfrom = ? or mto = ?", self.id, self.id)
    #ticket_ids = memos.pluck(:ticket_id)
    #Ticket.where("id IN (?)",ticket_ids).all
    Ticket.where(tuser: self.id)
  end

  def open_tickets
    self.tickets.select { |x| x.state == "open" }
  end

  def open_awaiting_tickets
    self.tickets.select { |x| (x.state == "open" && x.last_sayer_id != self.id) rescue nil }
  end


  def self.open_tickets_admin
    Ticket.where(state: "open").all
  end

  def self.open_awaiting_tickets_admin
    Ticket.where(state: "open").all.select do |ticket|
      (ticket.last_sayer.admin != true) rescue false
    end
  end

  def last_advert
    Advert.where(user_id: id).order(id: :asc).last
  end

  def has_unfinished_advert_creation
     last_advert && last_advert.completed != true
  end

  def nick
    self.email.split('@')[0].titleize
  end

  # given a negotiation, returns "s" if user is a seller in that negotiation,
  # "b" if buyer
  # "z" if neither
  def neg_role(n)
    ret_val = "z"
    ret_val = "b" if n.buyer_id == self.id
    ret_val = "s" if n.seller_id == self.id
  end
end

app/helpers/adverts_helper.rb
module AdvertsHelper
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/hits_helper.rb
module HitsHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/admin.html.slim
p foo

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kasa</title>
  <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css'  %>
  <%= stylesheet_link_tag    'https://fonts.googleapis.com/css?family=Lato:100,100italic,300,300italic,400,400italic,700,700italic,900italic,900' %>
  <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css' %>
  <%= stylesheet_link_tag    asset_url('style.css'), media: 'all' %>  
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%#= stylesheet_link_tag    'http://s3-us-west-2.amazonaws.com/pesticide/1.2.0/pesticide.min.css', media: 'all' %>
  <%= stylesheet_link_tag    'https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/5.3.2/css/bootstrap-slider.css' %>
  <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/owl.carousel.css' %>
  <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/owl.theme.css' %>
  <%= stylesheet_link_tag '/vendor/pickmeup.css' %>

  <%= csrf_meta_tags %>
</head>

<body class="<%= 'map-view' if session[:browse_view]  == 'Map' && params[:action] == 'browse' %>">

<%= yield %>


<%= javascript_include_tag 'application' %>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js">
<%= javascript_include_tag 'custom' %>
<%= javascript_include_tag 'jquery.scrollTo.min.js' %>
<%= javascript_include_tag 'https://code.jquery.com/ui/1.10.4/jquery-ui.js' %>
<%= javascript_include_tag 'http://maps.googleapis.com/maps/api/js?libraries=places' %>

<%= javascript_include_tag 'imgLiquid-min' %>



<%= javascript_include_tag 'bootstrap-slider.js' %>
<%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/owl.carousel.js' %>
<%= javascript_include_tag '/vendor/jquery.pickmeup.js' %>
</body>
</html>

app/views/navigation/_interior.html.erb
<nav class="interior navbar navbar-static-top">
  <div class="container-fluid">
    <div class="col-xs-12">
      <div class="row vertical-align">
        <div class="col-xs-4">
          <%= link_to (image_tag 'https://s3-us-west-2.amazonaws.com/kasa-dev/images/kasa-logo-black.svg', alt: 'Kasa', class: 'img-responsive'), root_path, class: 'navbar-brand' %>
        </div>
        <div class="col-xs-4 col-xs-offset-4">
          <div class="pull-right">
            <%= render 'navigation/rightitems' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/navigation/_main.html.erb
<nav class="navbar navbar-static-top">
  <div class="container-fluid">
    <div class="col-xs-12">
      <div class="row vertical-align">
        <div class="col-xs-4">
          <%= link_to (image_tag 'https://s3-us-west-2.amazonaws.com/kasa-dev/images/kasa-logo-white.svg', alt: 'Kasa', class: 'img-responsive'), root_path, class: 'navbar-brand' %>
        </div>
        <div class="col-xs-4 col-xs-offset-4">
          <div class="pull-right">
            <%= render 'navigation/rightitems' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/navigation/_rightitems.html.erb
<% if user_signed_in? %>
  <%= link_to 'Your Account', edit_user_registration_path, class: 'navi-links' %>
  <%= link_to "Sign Out", destroy_user_session_path, :method => :delete, class: 'navi-links activo' %>
<% else %>
  <%= link_to "Log In", new_user_session_path, class: 'navi-links' %>
  <%= link_to "Sign Up", new_user_registration_path, class: 'navi-links activo' %>
<% end %>

app/views/shared/_admin_footer.html.slim
<div class="page-footer">
  <div class="container"> 2014 © Stilt Media
  </div>
</div>

<div class="scroll-to-top" style="display: block;">
  <i class="icon-arrow-up"></i>
</div>

app/views/shared/_dashboard_bars.html.slim
section.dashboard-bar-1
  .row
    .col-md-12
      span.cell = link_to "Your Listings", user_adverts_path(current_user)
      span.cell = link_to "Create A Listing", "/adverts/new?step=1"
      - if current_user.admin
        span.cell = link_to "Admin Dashboard", "/pages/admin_dashboard"
      - else
        span.cell = link_to "Admin Dashboard", "javascript:alert('Restricted')"
      span.cell = link_to "Dashboard", "/pages/user_dashboard"


- if text2.size > 0
  section.dashboard-bar-2
    .row
      .col-md-12
        span #{text2}

app/views/shared/_footer.html.slim
/! footer
footer
  .container-fluid
    .row
      p We do not make or give any guarantee regarding, and assumes no responsibility for, any such decisions, nor any acts or omissions of lenders, brokers or other loan professionals, nor any result or consequence (direct or indirect) of any business transaction (actual, proposed or discussed) or related communications between lenders, brokers or other loan professionals and any other person, nor any rates, information or other content on or accessible through any website or app that did not originate solely from kasa-properties.com.



      span.border
      .copy-big
        .col-sm-8
          .copyrights
            p ©2015 KASA. All Rights Reserved.
            a href="/pages/untitled"  Privacy Policy
            a href="/pages/untitled"  Terms and Conditions
            a href="/pages/untitled"  FAQ
        .col-sm-4
          .social-icons.text-right
            a href="javascript:fbShare('http://kasa-staging.herokuapp.com/', 'Fb Share', 'Facebook share popup', 'http://goo.gl/dS52U', 520, 350)" 
              img alt="facebook" src=asset_path("icon_facebook.png")
            a.twitter.popup href="http://twitter.com/share"
              img alt="twitter" src=asset_path("icon_twitter.png")
            a href="https://plus.google.com/share?url=#{request.original_url}" onclick="javascript:window.open('https://plus.google.com/share?url=kasa-staging.herokuapp.com','','menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600'); return false;"
              img alt="google-plus" src=asset_path("icon_g_plus.png")



      /! for mobiles
      .copy-mobiles.text-center
        .col-sm-12
          .social-icons
            a href="/pages/untitled" 
              img alt="facebook" src=asset_path("icon_facebook.png")
            a href="/pages/untitled" 
              img alt="twitter" src=asset_path("icon_twitter.png")
            a href="/pages/untitled" 
              img alt="google-plus" src=asset_path("icon_g_plus.png")



        .col-sm-12
          .copyrights
            a href="/pages/untitled"  Privacy Policy
            a href="/pages/untitled"  Terms and Conditions
            a href="/pages/untitled"  FAQ
            p ©2015 KASA. All Rights Reserved.
      /! .for mobiles
/! .footer

app/views/shared/_listing_cell.html.slim
div class=(session[:browse_view]=='Map' ? '' : 'col-xs-8 col-xs-offset-2')
  .article
    .col-xs-12
      .listing-box.clearfix.center-block class=(session[:browse_view] == 'Map' ? 'skinny' : '')
        .col-xs-6.no-padding
          .image-box
            img alt="" src="http://kasa-staging-02.s3.amazonaws.com/#{property.listing_id}_0.jpg"
        .col-xs-6.no-padding
          .listing-box-content
            h5
              .prop_addr.invisible data-listingid=property.listing_id data-lat="" data-lng="" data-addr="#{property.address.titleize} #{property.city.titleize} #{property.state}" data-beds=property.beds data-baths=property.baths data-garage=property.garage data-price=number_to_currency(property.price, precision: 0) data-sf=property.sf = "#{property.address} #{property.zip} #{property.state} USA"
              a href="/pages/listing_details/#{property.listing_id}" = "#{property.address.titleize} #{property.city.titleize} #{property.state}"
            p.listing-price
              = number_to_currency(property.price, precision: 0)
              span = "$#{property.price/property.area}/sf" rescue ""
            ul.listing-info.list-unstyled.list-inline
              li
                img alt="" src=asset_path("pt_house_dark.png")
              li
                img alt="" src=asset_path("icon_couch_big.png")
                span = property.beds
              li
                img alt="" src=asset_path("icon_bathroom_big.png")
                span = property.baths
              li
                img alt="" src=asset_path("icon_car_big.png")
                span = property.garage
            .listing-box-footer
              p = "Listed #{distance_of_time_in_words_to_now(property.date)} ago"
              .links
                a.twitter.popup href="https://twitter.com/intent/tweet?text=Check+out+this+listing&url=http://kasa-staging.herokuapp.com/listings/#{property.listing_id}" Share
                a href="/pages/untitled"
                  div#my-share.share-widget data-url="#{@base_url}properties/#{property.listing_id}" data-text="Checkout out this listing" data-title="Share"
                - if user_signed_in?
                  - if property.is_favorite?(current_user)
                    a.favorite.fav-on href="javascript:void(0)" data-userid=current_user.id.to_s data-propertyid=property.id
                      i.favorite.fa.fa-heart
                      span &nbsp
                      span.words Favorite
                  - else
                    a.favorite href="javascript:void(0)" data-userid=current_user.id.to_s data-propertyid=property.id
                      i.favorite.fa.fa-heart
                      span &nbsp
                      span.words Favorite
                - else
                  a onclick="$(this).notify('You must be logged in to Favourite a listing');" href="javascript:;"  Favorite

app/views/shared/_listing_cell_myprops.html.slim
div class=(session[:browse_view]=='Map' ? '' : 'col-md-12')
  .article
    .col-xs-12
      .listing-box.clearfix.center-block class=(session[:browse_view] == 'Map' ? 'skinny' : '')
        .col-xs-6.no-padding
          .image-box
            img alt="" src="http://kasa-staging-02.s3.amazonaws.com/#{property.listing_id}_0.jpg"
        .col-xs-6.no-padding
          .listing-box-content
            h5
              .prop_addr.invisible data-listingid=property.listing_id data-lat="" data-lng="" data-addr="#{property.address.titleize rescue "Empty"} #{property.city.titleize rescue "Empty"} #{property.state}" data-beds=property.beds data-baths=property.baths data-garage=property.garage data-price=number_to_currency(property.price, precision: 0) data-sf=property.sf = "#{property.address} #{property.zip} #{property.state} USA"
              a href="/pages/listing_details/#{property.listing_id}" = "#{property.address.titleize rescue "Empty"} #{property.city.titleize rescue "Empty"} #{property.state}"
            p.listing-price
              = number_to_currency(property.price, precision: 0)
              span = "$#{property.price/property.area}/sf" rescue ""
            ul.listing-info.list-unstyled.list-inline
              li
                img alt="" src=asset_path("pt_house_dark.png")
              li
                img alt="" src=asset_path("icon_couch_big.png")
                span = property.beds
              li
                img alt="" src=asset_path("icon_bathroom_big.png")
                span = property.baths
              li
                img alt="" src=asset_path("icon_car_big.png")
                span = property.garage
            .listing-box-footer
              p = "Listed #{distance_of_time_in_words_to_now(property.date)} ago" rescue "Empty"
              .links
                a href="/adverts/#{advert.id}/edit" Edit
                = link_to 'Remove', advert_path(id: advert.id, redir_to: "back"), :method => :delete, :data => {:confirm => 'Are you sure?'}
                a href="/pages/untitled"
                  div#my-share.share-widget data-url="#{@base_url}properties/#{property.listing_id}" data-text="Checkout out this listing" data-title="Share"

app/views/shared/_open_house_times_edit.html.slim
- if advert.open_house_times.all.size == 0
  - OpenHouseTime.create(advert_id: advert.id )

/! OPEN HOUSE WIDGET
.row.open-house-times-edit-widget
  /! input
  .col-md-12
    - advert.open_house_times.all.each do |oht|
      .row
        .col-md-6
           /! .input
           .input-group
             h5 OPEN HOUSE DATE
             = best_in_place oht, :odate,  :inner_class => "w100pc", class: "look-like-input w100pc wsnw", :as => :date, :plac_holder => "Select Date"
        .col-md-3
           /! .input
           .input-group
             h5 START TIME
             = best_in_place oht, :start_time,  :inner_class => "w100pc", class: "look-like-input w100pc zwsnw",:as => :select, :place_holder => "Select Time", :collection => OpenHouseTime.times_collection
        .col-md-3
           /! .input
           .input-group
             h5 END TIME
             = best_in_place oht, :end_time,  :inner_class => "w100pc", class: "look-like-input w100pc zwsnw",:as => :select, :place_holder => "Select Time", :collection => OpenHouseTime.times_collection

  


    .row
      .col-md-3.col-md-offset-9
         .input-group
           h5
             a.add-another-day class=(review_mode ? "hide" : "") data-advertid=advert.id href="javascript:;" +  &nbsp;&nbsp;Add Another Day
  /! END OPEN HOUSE WIDGET

app/views/shared/_topbar.html.slim
.topbar
  something
    .container-fluid
      .row
        .col-xs-3
          a.logo href="/"
            img src=asset_url('Logo_dark.svg')
        .col-xs-9
          .actions.text-right
            - if user_signed_in?
              a.btn.btn-alt.login.invisible href="#"  Log In
              = link_to( pages_user_dashboard_path, { :class => 'btn btn-alt' } ) do
                i.icon.icon-grid &nbsp;
                = " Dashboard"

              = link_to( user_path(current_user), { :class => 'btn btn-alt', :style => "border: 0px" } ) do
                span.username.username-hide-mobile style=("color: black;")
                img.img-circle alt="" src="/users/#{current_user.id}/show_picture" style="zmargin-top: -8px; border: 0px; margin-right: 5px; height: 40px; zfloat: left;"

                = "#{current_user.email.split('@')[0].titleize}"
              = link_to( destroy_user_session_path, { :class => 'btn btn-alt logout', :method => :delete } ) do
                i.icon.icon-logout &nbsp;
                = " Logout"
            - else
              = link_to( new_user_session_path, { :class => 'btn btn-alt login' } ) do
                i.icon.icon-login &nbsp;
                = " Log In"

              = link_to( new_user_session_path, { :class => 'btn btn-alt login' } ) do
                i.icon.icon-user-follow &nbsp;
                = " Sign up"