config/routes.rb
Rails.application.routes.draw do
  resources :negotiations
  resources :open_house_times
  resources :memos
  resources :tickets
  resources :hits
  resources :feeds
  post '/adverts/:id/add_another_day' => 'adverts#add_another_day'
  resources :adverts
  resources :offers
  get '/pages/refresh_offers_portlet' => 'pages#refresh_offers_portlet'
  get '/properties/:id/images_tot' => 'properties#images_tot'
  post '/tickets/:id/add_memo' => 'tickets#add_memo'
  devise_for :users
  post '/users/:id' => 'users#update'
  get '/users/:id/show_picture' => 'users#show_picture'
  get '/offers/review/:id' => 'offers#review'
  get '/pages/view_offer/:id' => 'pages#view_offer'
  get '/users/create_admin'
  get '/users/:id' => 'users#show'
  post '/properties/img_post' => 'properties#img_post'
  post '/properties/img_rm' => 'properties#img_rm'
  get 'pages/more_filters'
  get 'pages/landing'
  get 'pages/browse'
  get 'pages/untitled'
  get 'pages/listing_details/:listing_id' => 'pages#listing_details'
  get 'pages/search'
  get 'pages/offer_1'
  get 'pages/offer_2'
  get 'pages/offer_3'
  get 'pages/offer_4'
  get 'pages/offer_5'
  get 'pages/offer_6'
  put '/pages/best_in_place_update'
  put '/pages/offer_5' => 'pages#put_todo'
  get '/pages/user_dashboard'
  get '/pages/admin_dashboard'
  post 'api/favorite_on'
  post 'api/favorite_off'
  root 'pages#landing'
  resources :users do
    resources :adverts
  end
  resources :properties

end

app/models/memo.rb
class Memo < ActiveRecord::Base
  belongs_to :ticket
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :set_memo, only: [:show, :edit, :update, :destroy]

  # GET /memos
  # GET /memos.json
  def index
    @memos = Memo.all
  end

  # GET /memos/1
  # GET /memos/1.json
  def show
  end

  # GET /memos/new
  def new
    @memo = Memo.new
  end

  # GET /memos/1/edit
  def edit
  end

  # POST /memos
  # POST /memos.json
  def create
    @memo = Memo.new(memo_params)

    respond_to do |format|
      if @memo.save
        format.html { head :ok }
        #format.json { render :show, status: :created, location: @memo }
        format.json { head :ok }
      else
        format.html { render :new }
        format.json { render json: @memo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memos/1
  # PATCH/PUT /memos/1.json
  def update
    respond_to do |format|
      if @memo.update(memo_params)
        format.html { redirect_to @memo, notice: 'Memo was successfully updated.' }
        format.json { render :show, status: :ok, location: @memo }
      else
        format.html { render :edit }
        format.json { render json: @memo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memos/1
  # DELETE /memos/1.json
  def destroy
    @memo.destroy
    respond_to do |format|
      format.html { redirect_to memos_url, notice: 'Memo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_memo
      @memo = Memo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def memo_params
      params.require(:memo).permit(:mfrom, :mto, :body, :ticket_id)
    end
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/views/memos/_form.html.slim
= form_for @memo do |f|
  - if @memo.errors.any?
    #error_explanation
      h2 = "#{pluralize(@memo.errors.count, "error")} prohibited this memo from being saved:"
      ul
        - @memo.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :from
    = f.text_field :from
  .field
    = f.label :to
    = f.text_field :to
  .field
    = f.label :body
    = f.text_field :body
  .field
    = f.label :ticket
    = f.text_field :ticket
  .actions = f.submit

app/views/memos/_form2.html.slim
= form_for(@new_memo, remote: true) do |f|
  - if @new_memo.errors.any?
    #error_explanation
      h2 = "#{pluralize(@new_memo.errors.count, "error")} prohibited this memo from being saved:"
      ul
        - @new_memo.errors.full_messages.each do |message|
          li = message
  .field
    = f.hidden_field :mfrom
  .field
    = f.text_area :body, cols: "80", rows: "4" 
  .field
    = f.hidden_field :ticket_id
  .actions = f.submit "Reply", class: "btn green"

app/views/memos/edit.html.slim
h1 Editing memo

== render 'form'

= link_to 'Show', @memo
'|
= link_to 'Back', memos_path

app/views/memos/index.html.slim
h1 Listing memos

table
  thead
    tr
      th From
      th To
      th Body
      th Ticket
      th
      th
      th

  tbody
    - @memos.each do |memo|
      tr
        td = memo.from
        td = memo.to
        td = memo.body
        td = memo.ticket
        td = link_to 'Show', memo
        td = link_to 'Edit', edit_memo_path(memo)
        td = link_to 'Destroy', memo, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Memo', new_memo_path

app/views/memos/new.html.slim
h1 New memo

== render 'form'

= link_to 'Back', memos_path

app/views/memos/show.html.slim
p#notice = notice

p
  strong From:
  = @memo.from
p
  strong To:
  = @memo.to
p
  strong Body:
  = @memo.body
p
  strong Ticket:
  = @memo.ticket

= link_to 'Edit', edit_memo_path(@memo)
'|
= link_to 'Back', memos_path